version: '3.8'

services:
  waha:
    image: devlikeapro/waha:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      WHATSAPP_DEFAULT_ENGINE: WEBJS
      WAHA_API_KEY: minha-chave-super-segura
      WAHA_PRINT_QR: "true"
      WAHA_LOG_LEVEL: info
      WAHA_SESSION_STORE_TYPE: FILE
      WAHA_DASHBOARD_USERNAME: admin
      WAHA_DASHBOARD_PASSWORD: admin123
      WHATSAPP_SWAGGER_USERNAME: admin
      WHATSAPP_SWAGGER_PASSWORD: admin123

      # WHATSAPP_HOOK_EVENTS: message,message.any
      # WHATSAPP_HOOK_URL: ${BACKEND_API_URL}/api/whatsapp/webhook
      # WHATSAPP_HOOK_HMAC: secret_para_validar_entrada_de_mensagens
      # x-webhook-secret: secret_para_validar_entrada_de_mensagens

      # Formato novo (WAHA 2026+)
      WAHA_WEBHOOK_URL: ${BACKEND_API_URL}/api/whatsapp/webhook
      WAHA_WEBHOOK_EVENTS: message,message.any

      # Notificação de sessão desconectada → backend → Replay Agente
      WAHA_WEBHOOK_URL2: ${BACKEND_API_URL}/api/whatsapp/session-status
      WAHA_WEBHOOK_EVENTS2: session.status
    volumes:
      - waha_sessions:/app/.sessions

volumes:
  waha_sessions: