-- AlterTable: add WELL_STOCKED to TemplateTrigger enum
ALTER TABLE `message_templates` MODIFY COLUMN `trigger` ENUM('FIRST_CONTACT', 'REPLENISHMENT_REMINDER', 'REPLENISHMENT_OVERDUE', 'RETRY_1H', 'RETRY_3H', 'RETRY_24H', 'CUSTOM', 'WELL_STOCKED') NOT NULL DEFAULT 'CUSTOM';
